##
## Build
##

FROM golang:1.16-buster AS build

WORKDIR /Docker

COPY go.mod ./
# COPY go.sum ./
RUN go mod download

COPY *.go ./

RUN go build -o /docker-cdht

##
## Deploy
##

FROM gcr.io/distroless/base-debian10

WORKDIR /

COPY --from=build /docker-cdht /docker-cdht

# EXPOSE 443

USER nonroot:nonroot

ENTRYPOINT ["/docker-cdht"]
