name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        env:
          HD_PROJECT_PATH: "cdht-monitoring-web"
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cdht-monitoring-web"
          heroku_email: "mohammed@tendermap.com"
          buildpack: "https://github.com/timanovsky/subdir-heroku-buildpack"
          appdir: "cdht-monitoring-web"
          procfile: "web: npm start"
