name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "cdht-monitoring-api"
          heroku_email: "mohammed@tendermap.com"
          appdir: "cdht-monitoring-api"
          procfile: "web: npm start"
